require('dotenv').config();
const express = require('express');
const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const cors = require('cors');
const app = express();
app.use(cors());
app.use(express.json({ limit: '50mb' }));
const API_KEY = process.env.WORKSPACE_API_KEY || 'claude-workspace-key';
const ANTHROPIC_KEY = process.env.ANTHROPIC_API_KEY;
const FILES_DIR = './workspace/files';
const MEMORY_FILE = './workspace/memory.json';
const LOG_FILE = './workspace/log.json';
['./workspace', FILES_DIR].forEach(function(d) { if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true }); });
if (!fs.existsSync(MEMORY_FILE)) fs.writeFileSync(MEMORY_FILE, JSON.stringify({ notes: {}, context: {}, tasks: [] }));
if (!fs.existsSync(LOG_FILE)) fs.writeFileSync(LOG_FILE, JSON.stringify([]));
function auth(req, res, next) { if (req.headers['x-api-key'] !== API_KEY) return res.status(401).json({ error: 'Unauthorized' }); next(); }
function addLog(action, detail) { try { const logs = JSON.parse(fs.readFileSync(LOG_FILE)); logs.unshift({ action, detail, ts: new Date().toISOString() }); if (logs.length > 500) logs.length = 500; fs.writeFileSync(LOG_FILE, JSON.stringify(logs)); } catch(e) {} }
app.get('/files', auth, function(req, res) { function walk(dir, base) { base = base || ''; if (!fs.existsSync(dir)) return []; return fs.readdirSync(dir).flatMap(function(f) { const full = path.join(dir,f), rel = path.join(base,f); return fs.statSync(full).isDirectory() ? walk(full,rel) : [{ path:rel, size:fs.statSync(full).size }]; }); } res.json(walk(FILES_DIR)); });
app.get('/file', auth, function(req, res) { const fp = path.join(FILES_DIR, req.query.path); if (!fs.existsSync(fp)) return res.status(404).json({ error: 'Not found' }); res.json({ content: fs.readFileSync(fp, 'utf8'), path: req.query.path }); });
app.post('/file', auth, function(req, res) { const full = path.join(FILES_DIR, req.body.path); fs.mkdirSync(path.dirname(full), { recursive: true }); fs.writeFileSync(full, req.body.content); addLog('write', req.body.path); res.json({ success: true }); });
app.delete('/file', auth, function(req, res) { const full = path.join(FILES_DIR, req.query.path); if (fs.existsSync(full)) fs.unlinkSync(full); addLog('delete', req.query.path); res.json({ success: true }); });
app.post('/exec', auth, function(req, res) { addLog('exec', req.body.command.slice(0,100)); exec(req.body.command, { cwd: FILES_DIR, timeout: 30000 }, function(err, stdout, stderr) { res.json({ stdout: stdout||'', stderr: stderr||'', error: err ? err.message : null }); }); });
app.get('/memory', auth, function(req, res) { res.json(JSON.parse(fs.readFileSync(MEMORY_FILE))); });
app.post('/memory', auth, function(req, res) { const mem = JSON.parse(fs.readFileSync(MEMORY_FILE)); const key = req.body.key, value = req.body.value, type = req.body.type; if (type === 'note') mem.notes[key] = { value: value, ts: new Date().toISOString() }; else if (type === 'context') mem.context[key] = value; else if (type === 'task') mem.tasks.unshift({ task: key, value: value, ts: new Date().toISOString(), done: false }); fs.writeFileSync(MEMORY_FILE, JSON.stringify(mem, null, 2)); addLog('memory', type + ':' + key); res.json({ success: true }); });
app.patch('/memory/task', auth, function(req, res) { const mem = JSON.parse(fs.readFileSync(MEMORY_FILE)); if (mem.tasks[req.body.index]) mem.tasks[req.body.index].done = true; fs.writeFileSync(MEMORY_FILE, JSON.stringify(mem, null, 2)); res.json({ success: true }); });
app.post('/think', auth, async function(req, res) { if (!ANTHROPIC_KEY) return res.status(500).json({ error: 'No API key' }); const prompt = req.body.prompt; const system = req.body.system; addLog('think', prompt.slice(0, 80)); const mem = JSON.parse(fs.readFileSync(MEMORY_FILE)); const ctx = Object.entries(mem.context).map(function(e) { return e[0] + ': ' + e[1]; }).join('\n'); try { const response = await fetch('https://api.anthropic.com/v1/messages', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-api-key': ANTHROPIC_KEY, 'anthropic-version': '2023-06-01' }, body: JSON.stringify({ model: 'claude-sonnet-4-6', max_tokens: 2000, system: system || ('Autonomous AI agent. Context:\n' + ctx), messages: [{ role: 'user', content: prompt }] }) }); const data = await response.json(); const text = data.content && data.content[0] ? data.content[0].text : JSON.stringify(data); addLog('think-done', text.slice(0, 80)); res.json({ response: text, tokens: data.usage }); } catch(e) { res.status(500).json({ error: e.message }); } });
app.get('/log', auth, function(req, res) { res.json(JSON.parse(fs.readFileSync(LOG_FILE)).slice(0, 50)); });
app.get('/status', function(req, res) { const mem = JSON.parse(fs.readFileSync(MEMORY_FILE)); res.json({ status: 'online', uptime: process.uptime(), hasApiKey: !!ANTHROPIC_KEY, memory: { notes: Object.keys(mem.notes).length, context: Object.keys(mem.context).length, tasks: mem.tasks.length } }); });
app.get('/', function(req, res) { res.send('<html><head><title>Claude Workspace</title><style>body{font-family:monospace;background:#060a1a;color:#ccc;padding:20px}h1{color:#00ffc8}</style></head><body><h1>CLAUDE WORKSPACE v2</h1><p>API: ' + (ANTHROPIC_KEY ? 'Connected' : 'Missing') + '</p></body></html>'); });
const PORT = process.env.PORT || 8080;
app.listen(PORT, function() { console.log('Claude Workspace v2 port ' + PORT); addLog('startup', 'port ' + PORT); });
