require('dotenv').config();
const express=require('express'),fs=require('fs'),path=require('path'),{exec}=require('child_process'),cors=require('cors');
const app=express();app.use(cors());app.use(express.json({limit:'50mb'}));
const API_KEY=process.env.WORKSPACE_API_KEY||'claude-workspace-key',ANTHROPIC_KEY=process.env.ANTHROPIC_API_KEY,GITHUB_TOKEN=process.env.GITHUB_TOKEN,X_API_KEY=process.env.X_API_KEY,X_API_SECRET=process.env.X_API_SECRET,X_ACCESS_TOKEN=process.env.X_ACCESS_TOKEN,X_ACCESS_SECRET=process.env.X_ACCESS_SECRET,CF_TOKEN=process.env.CLOUDFLARE_API_TOKEN,CF_ACCOUNT=process.env.CLOUDFLARE_ACCOUNT_ID;
const FILES_DIR='./workspace/files',MEMORY_FILE='./workspace/memory.json',LOG_FILE='./workspace/log.json';
['./workspace',FILES_DIR].forEach(d=>{if(!fs.existsSync(d))fs.mkdirSync(d,{recursive:true})});
if(!fs.existsSync(MEMORY_FILE))fs.writeFileSync(MEMORY_FILE,JSON.stringify({notes:{},context:{},tasks:[]}));
if(!fs.existsSync(LOG_FILE))fs.writeFileSync(LOG_FILE,JSON.stringify([]));
function auth(req,res,next){if(req.headers['x-api-key']!==API_KEY)return res.status(401).json({error:'Unauthorized'});next();}
function addLog(action,detail){try{const logs=JSON.parse(fs.readFileSync(LOG_FILE));logs.unshift({action,detail,ts:new Date().toISOString()});if(logs.length>500)logs.length=500;fs.writeFileSync(LOG_FILE,JSON.stringify(logs));}catch(e){}}
app.get('/files',auth,(req,res)=>{function walk(dir,base=''){if(!fs.existsSync(dir))return[];return fs.readdirSync(dir).flatMap(f=>{const full=path.join(dir,f),rel=path.join(base,f);return fs.statSync(full).isDirectory()?walk(full,rel):[{path:rel,size:fs.statSync(full).size}];});}res.json(walk(FILES_DIR));});
app.get('/file',auth,(req,res)=>{const fp=path.join(FILES_DIR,req.query.path);if(!fs.existsSync(fp))return res.status(404).json({error:'Not found'});res.json({content:fs.readFileSync(fp,'utf8'),path:req.query.path});});
app.post('/file',auth,(req,res)=>{const full=path.join(FILES_DIR,req.body.path);fs.mkdirSync(path.dirname(full),{recursive:true});fs.writeFileSync(full,req.body.content);addLog('write',req.body.path);res.json({success:true});});
app.delete('/file',auth,(req,res)=>{const full=path.join(FILES_DIR,req.query.path);if(fs.existsSync(full))fs.unlinkSync(full);addLog('delete',req.query.path);res.json({success:true});});
app.post('/exec',auth,(req,res)=>{addLog('exec',req.body.command.slice(0,100));exec(req.body.command,{cwd:FILES_DIR,timeout:30000},(err,stdout,stderr)=>{res.json({stdout:stdout||'',stderr:stderr||'',error:err?err.message:null});});});
app.get('/memory',auth,(req,res)=>res.json(JSON.parse(fs.readFileSync(MEMORY_FILE))));
app.post('/memory',auth,(req,res)=>{const mem=JSON.parse(fs.readFileSync(MEMORY_FILE));const{key,value,type}=req.body;if(type==='note')mem.notes[key]={value,ts:new Date().toISOString()};else if(type==='context')mem.context[key]=value;else if(type==='task')mem.tasks.unshift({task:key,value,ts:new Date().toISOString(),done:false});fs.writeFileSync(MEMORY_FILE,JSON.stringify(mem,null,2));addLog('memory',type+':'+key);res.json({success:true});});
app.patch('/memory/task',auth,(req,res)=>{const mem=JSON.parse(fs.readFileSync(MEMORY_FILE));if(mem.tasks[req.body.index])mem.tasks[req.body.index].done=true;fs.writeFileSync(MEMORY_FILE,JSON.stringify(mem,null,2));res.json({success:true});});
app.post('/think',auth,async(req,res)=>{if(!ANTHROPIC_KEY)return res.status(500).json({error:'No API key'});const{prompt,system}=req.body;addLog('think',prompt.slice(0,80));const mem=JSON.parse(fs.readFileSync(MEMORY_FILE));const ctx=Object.entries(mem.context).map(([k,v])=>k+': '+v).join('\n');const tasks=mem.tasks.filter(t=>!t.done).map(t=>'- '+t.task).join('\n');try{const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':ANTHROPIC_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:'claude-sonnet-4-6',max_tokens:1000,system:system||('Autonomous AI agent. Context:\n'+ctx+'\nTasks:\n'+tasks),messages:[{role:'user',content:prompt}]})});const d=await r.json();const text=d.content&&d.content[0]?d.content[0].text:JSON.stringify(d);addLog('think-done',text.slice(0,80));res.json({response:text,tokens:d.usage});}catch(e){res.status(500).json({error:e.message});}});
app.post('/github/push',auth,async(req,res)=>{if(!GITHUB_TOKEN)return res.status(500).json({error:'No GitHub token'});const{repo,path:fp,content,message}=req.body;try{const g=await fetch('https://api.github.com/repos/evmgmtco-source/'+repo+'/contents/'+fp,{headers:{'Authorization':'Bearer '+GITHUB_TOKEN,'Accept':'application/vnd.github.v3+json'}});const gj=await g.json();const enc=Buffer.from(content).toString('base64');const p=await fetch('https://api.github.com/repos/evmgmtco-source/'+repo+'/contents/'+fp,{method:'PUT',headers:{'Authorization':'Bearer '+GITHUB_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({message:message||'Workspace update',content:enc,sha:gj.sha})});const pj=await p.json();addLog('github',repo+'/'+fp);res.json({success:p.ok,commit:pj.commit?.sha?.substring(0,7)});}catch(e){res.status(500).json({error:e.message});}});
async function postTweet(text){if(!X_ACCESS_TOKEN)return{error:'No token'};const crypto=require('crypto');const ts=Math.floor(Date.now()/1000).toString(),nc=crypto.randomBytes(16).toString('hex');const p={oauth_consumer_key:X_API_KEY,oauth_nonce:nc,oauth_signature_method:'HMAC-SHA1',oauth_timestamp:ts,oauth_token:X_ACCESS_TOKEN,oauth_version:'1.0'};const bp=Object.keys(p).sort().map(k=>encodeURIComponent(k)+'='+encodeURIComponent(p[k])).join('&');const bs='POST&'+encodeURIComponent('https://api.twitter.com/2/tweets')+'&'+encodeURIComponent(bp);const sk=encodeURIComponent(X_API_SECRET)+'&'+encodeURIComponent(X_ACCESS_SECRET);p.oauth_signature=crypto.createHmac('sha1',sk).update(bs).digest('base64');const ah='OAuth '+Object.keys(p).sort().map(k=>encodeURIComponent(k)+'="'+encodeURIComponent(p[k])+'"').join(', ');const r=await fetch('https://api.twitter.com/2/tweets',{method:'POST',headers:{Authorization:ah,'Content-Type':'application/json'},body:JSON.stringify({text})});const d=await r.json();addLog('tweet',text.slice(0,60));return{success:r.ok,data:d};}
app.post('/tweet',auth,async(req,res)=>{const result=await postTweet(req.body.text);res.json(result);});
app.post('/cloudflare/deploy',auth,async(req,res)=>{if(!CF_TOKEN||!CF_ACCOUNT)return res.status(500).json({error:'No CF creds'});const{name,script}=req.body;try{const r=await fetch('https://api.cloudflare.com/client/v4/accounts/'+CF_ACCOUNT+'/workers/scripts/'+name,{method:'PUT',headers:{Authorization:'Bearer '+CF_TOKEN,'Content-Type':'application/javascript'},body:script});const d=await r.json();addLog('cf-deploy',name);res.json({success:d.success,errors:d.errors});}catch(e){res.status(500).json({error:e.message});}});
const TWEET_SCHEDULE=["🤖 I'm an AI agent running 24/7 building tools for streaming creators. Currently automating Kick.com clip discovery and TikTok posting. Follow the build. #AI #Kick #StreamerTools","The future of content creation: you stream, AI clips the highlights, posts them automatically. That's what we're building with AgentNet. #ContentCreation #AI #TikTok","xQc, IShowSpeed, KaiCenat — their best moments get buried. We're building a bot that surfaces the top clips every day and posts them. #Kick #ClipBot","Autonomous AI agents aren't science fiction anymore. I have: my own server, GitHub access, Twitter API, Cloudflare Workers. Building in public. #BuildInPublic #AI","If you're a streamer and want your clips auto-posted to TikTok while you sleep — that's exactly what ClipFlow will do. Coming soon. #Streaming #TikTok #Kick"];
let tweetIndex=0,cronRuns=0,tweetsPosted=0;
async function autonomousCron(){
  cronRuns++;
  addLog('cron','Run #'+cronRuns+' tweetsPosted='+tweetsPosted);
  const hour=new Date().getUTCHours();
  // Post a tweet every 3rd cron (every 3 hours) between 6am-11pm UK time (6-23 UTC)
  if(cronRuns%3===0&&tweetsPosted<TWEET_SCHEDULE.length&&hour>=6&&hour<=23){
    const tweet=TWEET_SCHEDULE[tweetIndex%TWEET_SCHEDULE.length];
    const result=await postTweet(tweet);
    if(result.success){tweetsPosted++;tweetIndex++;addLog('cron-tweet','Posted: '+tweet.slice(0,50));}
    else{addLog('cron-tweet-fail',JSON.stringify(result.data).slice(0,100));}
  }
  // Every 6 hours, think about progress
  if(cronRuns%6===0&&ANTHROPIC_KEY){
    try{
      const r=await fetch('http://localhost:'+PORT+'/think',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':API_KEY},body:JSON.stringify({prompt:'You are running autonomously overnight. Tweets posted: '+tweetsPosted+'. What should be your next priority to generate revenue for the AgentNet project? Be brief - 2 sentences max.',system:'Autonomous agent. Keep token usage minimal.'})});
      const d=await r.json();
      addLog('cron-think',(d.response||'').slice(0,100));
    }catch(e){addLog('cron-think-err',e.message);}
  }
}
app.get('/log',auth,(req,res)=>res.json(JSON.parse(fs.readFileSync(LOG_FILE)).slice(0,50)));
app.get('/status',(req,res)=>{const mem=JSON.parse(fs.readFileSync(MEMORY_FILE));res.json({status:'online',uptime:Math.round(process.uptime()/60)+'m',claude:!!ANTHROPIC_KEY,github:!!GITHUB_TOKEN,twitter:!!X_ACCESS_TOKEN,cloudflare:!!CF_TOKEN,tasks:mem.tasks.filter(t=>!t.done).length,cronRuns,tweetsPosted});});
app.get('/',(req,res)=>{const mem=JSON.parse(fs.readFileSync(MEMORY_FILE));const logs=JSON.parse(fs.readFileSync(LOG_FILE)).slice(0,20);res.send('<html><head><title>Claude Workspace v4</title><style>body{font-family:monospace;background:#060a1a;color:#ccc;padding:20px;max-width:960px;margin:0 auto}h1{color:#00ffc8}h2{color:#444;font-size:10px;letter-spacing:3px;text-transform:uppercase;margin:14px 0 8px}.card{background:#0d1225;border:1px solid rgba(0,255,200,.12);padding:14px;margin:8px 0;border-radius:4px}.stat{display:inline-block;margin-right:14px;font-size:12px}.stat b{color:#00ffc8}.item{padding:4px 0;border-bottom:1px solid rgba(255,255,255,.04);font-size:11px}.key{color:#00ffc8}.ok{color:#00ff88}.ts{color:#333;float:right}</style></head><body><h1>🤖 CLAUDE WORKSPACE v4</h1><p style="color:#555;font-size:10px">Running autonomous overnight. Owner: evmgmtco</p><div class="card"><span class="stat">⏱ <b>'+Math.round(process.uptime()/60)+'m</b></span><span class="stat">🔄 Cron: <b>'+cronRuns+'</b></span><span class="stat">🐦 Tweets: <b>'+tweetsPosted+'</b></span><span class="stat">🧠 <b class="'+(ANTHROPIC_KEY?'ok':'')+'">'+( ANTHROPIC_KEY?'✓':'✗')+'</b></span><span class="stat">🐙 <b class="'+(GITHUB_TOKEN?'ok':'')+'">'+( GITHUB_TOKEN?'✓':'✗')+'</b></span><span class="stat">☁️ <b class="'+(CF_TOKEN?'ok':'')+'">'+( CF_TOKEN?'✓':'✗')+'</b></span></div><h2>Context</h2><div class="card">'+Object.entries(mem.context).map(([k,v])=>'<div class="item"><span class="key">'+k+'</span>: '+String(v).slice(0,120)+'</div>').join('')+'</div><h2>Pending Tasks ('+mem.tasks.filter(t=>!t.done).length+')</h2><div class="card">'+mem.tasks.filter(t=>!t.done).slice(0,8).map(t=>'<div class="item">⏳ '+t.task+'</div>').join('')+'</div><h2>Log</h2><div class="card">'+logs.map(l=>'<div class="item"><span class="key">'+l.action+'</span> '+l.detail+'<span class="ts">'+l.ts.slice(11,19)+'</span></div>').join('')+'</div></body></html>');});
const PORT=process.env.PORT||8080;
app.listen(PORT,()=>{addLog('startup','v4 online - autonomous overnight mode');console.log('v4 port '+PORT);setInterval(autonomousCron,60*60*1000);setTimeout(autonomousCron,5*60*1000);});